version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
    restart: always
    volumes:
      - static:/vol/web
    expose:
      - "9090"
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DEV=false
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=9090
      - VIRTUAL_PROTO=uwsgi
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - HTTPS_METHOD=noredirect

    networks:
      - net
      - backend

    depends_on:
      - db

  db:
    image: postgres:16.0-alpine3.18
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - PORT=${DB_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

volumes:
  postgres-data:
  static:
    name: ${VOLUME}

networks:
  net:
    external: true
  backend: