version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app
      - dev-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db && python manage.py migrate && python manage.py runserver 0.0.0.0:9000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=development
      - DEBUG=1
      - DEV=true
    networks:
      - dev-net
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  db:
    image: postgres:16.0-alpine3.18
    volumes:
      - dev-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-q", "-d", "{DB_NAME}", "-U", "{DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=development
    networks:
      - dev-net

volumes:
  dev-data:
  dev-db:

networks:
  dev-net:
    driver: bridge