# Generated by Django 4.2.5 on 2024-10-07 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_todo_last_added_alter_todo_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ["ordering"]},
        ),
    ]
