---
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  tests:
    name: Execute Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout and Copy Repo
        uses: actions/checkout@v4
      - run: |
          mkdir ../build
          cp -TR . ../build
          tar -cvf deploy.tar ../build/

      - name: Install SSH Key
        uses: up9cloud/action-rsync@master
        env:
          HOST: ${{ secrets.HOST_DNS }}
          KEY: ${{ secrets.EC2_SSH_KEY }}
          USER: ${{ secrets.USERNAME }}
          SOURCE: "./deploy.tar"
          TARGET: /home/ec2-user/

  build:
    name: Build App
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Execute Build Commands For Deployed App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            tar -xvf ~/deploy.tar
            cd ~/todo_api
            chmod +x ./setups/setup_env.sh
            ./setups/setup_env.sh
            docker-compose -f ./docker-compose-build.yml build
            docker-compose -f ./docker-compose-build.yml up